package views.enums;

public enum ViewName {
    LOGIN,
    REGISTER,
    ACCOUNT_MANAGEMENT,
    USAGER_LIST,
    ADMIN_DASHBOARD,
    DEMANDS_MANAGEMENT,
    DEMAND_DETAILS,
    USER_DASHBOARD,
    DEMANDES,
    ACTES
}
